CREATE EXTENSION IF NOT EXISTS "pgcrypto";

CREATE TYPE "TransactionKind" AS ENUM ('OPENING', 'INCOME', 'EXPENSE');
CREATE TYPE "FxSource" AS ENUM ('MARKET', 'MANUAL');

CREATE TABLE "Currency" ("code" VARCHAR(3) NOT NULL, "precision" INTEGER NOT NULL, CONSTRAINT "Currency_pkey" PRIMARY KEY ("code"));
INSERT INTO "Currency" ("code", "precision") VALUES ('USD', 2), ('EUR', 2), ('VES', 2), ('GBP', 2) ON CONFLICT ("code") DO NOTHING;
CREATE TABLE "User" ("id" UUID NOT NULL DEFAULT gen_random_uuid(), "email" TEXT NOT NULL, "passwordHash" TEXT NOT NULL, "createdAt" TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMPTZ(3) NOT NULL, CONSTRAINT "User_pkey" PRIMARY KEY ("id"));
CREATE UNIQUE INDEX "User_email_key" ON "User"("email");
CREATE TABLE "UserPreferences" ("id" UUID NOT NULL DEFAULT gen_random_uuid(), "userId" UUID NOT NULL, "baseCurrency" VARCHAR(3) NOT NULL, "timezone" TEXT NOT NULL, "onboardingComplete" BOOLEAN NOT NULL DEFAULT false, CONSTRAINT "UserPreferences_pkey" PRIMARY KEY ("id"));
CREATE UNIQUE INDEX "UserPreferences_userId_key" ON "UserPreferences"("userId");
CREATE TABLE "Account" ("id" UUID NOT NULL DEFAULT gen_random_uuid(), "userId" UUID NOT NULL, "name" TEXT NOT NULL, "currencyCode" VARCHAR(3) NOT NULL, "openingBalance" DECIMAL(20,8) NOT NULL, "archivedAt" TIMESTAMPTZ(3), "createdAt" TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMPTZ(3) NOT NULL, CONSTRAINT "Account_pkey" PRIMARY KEY ("id"));
CREATE INDEX "Account_userId_archivedAt_idx" ON "Account"("userId", "archivedAt");
CREATE TABLE "Transfer" ("id" UUID NOT NULL DEFAULT gen_random_uuid(), "userId" UUID NOT NULL, "sourceAccountId" UUID NOT NULL, "destinationAccountId" UUID NOT NULL, "sourceAmount" DECIMAL(20,8) NOT NULL, "destinationAmount" DECIMAL(20,8) NOT NULL, "sourceCurrency" VARCHAR(3) NOT NULL, "destinationCurrency" VARCHAR(3) NOT NULL, "feeAmount" DECIMAL(20,8), "occurredAt" TIMESTAMPTZ(3) NOT NULL, "createdAt" TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, CONSTRAINT "Transfer_pkey" PRIMARY KEY ("id"));
CREATE INDEX "Transfer_userId_occurredAt_idx" ON "Transfer"("userId", "occurredAt");
CREATE TABLE "Transaction" ("id" UUID NOT NULL DEFAULT gen_random_uuid(), "userId" UUID NOT NULL, "accountId" UUID NOT NULL, "kind" "TransactionKind" NOT NULL, "amount" DECIMAL(20,8) NOT NULL, "currencyCode" VARCHAR(3) NOT NULL, "occurredAt" TIMESTAMPTZ(3) NOT NULL, "note" TEXT, "voidedAt" TIMESTAMPTZ(3), "voidReason" TEXT, "transferId" UUID, "createdAt" TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, CONSTRAINT "Transaction_pkey" PRIMARY KEY ("id"));
CREATE INDEX "Transaction_userId_occurredAt_idx" ON "Transaction"("userId", "occurredAt");
CREATE INDEX "Transaction_accountId_occurredAt_idx" ON "Transaction"("accountId", "occurredAt");
CREATE TABLE "LedgerEntry" ("id" UUID NOT NULL DEFAULT gen_random_uuid(), "transactionId" UUID NOT NULL, "accountId" UUID NOT NULL, "signedAmount" DECIMAL(20,8) NOT NULL, "createdAt" TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, CONSTRAINT "LedgerEntry_pkey" PRIMARY KEY ("id"));
CREATE INDEX "LedgerEntry_accountId_createdAt_idx" ON "LedgerEntry"("accountId", "createdAt");
CREATE TABLE "FxRate" ("id" UUID NOT NULL DEFAULT gen_random_uuid(), "baseCode" VARCHAR(3) NOT NULL, "quoteCode" VARCHAR(3) NOT NULL, "rate" DECIMAL(24,12) NOT NULL, "effectiveAt" TIMESTAMPTZ(3) NOT NULL, "source" "FxSource" NOT NULL, "createdAt" TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, CONSTRAINT "FxRate_pkey" PRIMARY KEY ("id"));
CREATE INDEX "FxRate_baseCode_quoteCode_effectiveAt_idx" ON "FxRate"("baseCode", "quoteCode", "effectiveAt");
CREATE TABLE "FxSnapshot" ("id" UUID NOT NULL DEFAULT gen_random_uuid(), "transferId" UUID NOT NULL, "effectiveAt" TIMESTAMPTZ(3) NOT NULL, "source" "FxSource" NOT NULL, "createdAt" TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, CONSTRAINT "FxSnapshot_pkey" PRIMARY KEY ("id"));
CREATE UNIQUE INDEX "FxSnapshot_transferId_key" ON "FxSnapshot"("transferId");
CREATE TABLE "FxSnapshotRate" ("id" UUID NOT NULL DEFAULT gen_random_uuid(), "snapshotId" UUID NOT NULL, "baseCode" VARCHAR(3) NOT NULL, "quoteCode" VARCHAR(3) NOT NULL, "rate" DECIMAL(24,12) NOT NULL, CONSTRAINT "FxSnapshotRate_pkey" PRIMARY KEY ("id"));
CREATE UNIQUE INDEX "FxSnapshotRate_snapshotId_baseCode_quoteCode_key" ON "FxSnapshotRate"("snapshotId", "baseCode", "quoteCode");
CREATE TABLE "RefreshSession" ("id" UUID NOT NULL DEFAULT gen_random_uuid(), "userId" UUID NOT NULL, "familyId" UUID NOT NULL, "tokenHash" TEXT NOT NULL, "expiresAt" TIMESTAMPTZ(3) NOT NULL, "revokedAt" TIMESTAMPTZ(3), "createdAt" TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, CONSTRAINT "RefreshSession_pkey" PRIMARY KEY ("id"));
CREATE UNIQUE INDEX "RefreshSession_tokenHash_key" ON "RefreshSession"("tokenHash");
CREATE INDEX "RefreshSession_userId_familyId_idx" ON "RefreshSession"("userId", "familyId");
CREATE TABLE "PasswordResetToken" ("id" UUID NOT NULL DEFAULT gen_random_uuid(), "userId" UUID NOT NULL, "tokenHash" TEXT NOT NULL, "expiresAt" TIMESTAMPTZ(3) NOT NULL, "usedAt" TIMESTAMPTZ(3), CONSTRAINT "PasswordResetToken_pkey" PRIMARY KEY ("id"));
CREATE UNIQUE INDEX "PasswordResetToken_tokenHash_key" ON "PasswordResetToken"("tokenHash");
CREATE TABLE "AuditEvent" ("id" UUID NOT NULL DEFAULT gen_random_uuid(), "userId" UUID NOT NULL, "action" TEXT NOT NULL, "targetId" TEXT NOT NULL, "reason" TEXT, "metadata" JSONB, "createdAt" TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, CONSTRAINT "AuditEvent_pkey" PRIMARY KEY ("id"));
CREATE INDEX "AuditEvent_userId_createdAt_idx" ON "AuditEvent"("userId", "createdAt");
CREATE TABLE "IdempotencyKey" ("id" UUID NOT NULL DEFAULT gen_random_uuid(), "userId" UUID NOT NULL, "key" TEXT NOT NULL, "fingerprint" TEXT NOT NULL, "response" JSONB NOT NULL, "createdAt" TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, CONSTRAINT "IdempotencyKey_pkey" PRIMARY KEY ("id"));
CREATE UNIQUE INDEX "IdempotencyKey_userId_key_key" ON "IdempotencyKey"("userId", "key");

ALTER TABLE "UserPreferences" ADD CONSTRAINT "UserPreferences_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "UserPreferences" ADD CONSTRAINT "UserPreferences_baseCurrency_fkey" FOREIGN KEY ("baseCurrency") REFERENCES "Currency"("code") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "Account" ADD CONSTRAINT "Account_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "Account" ADD CONSTRAINT "Account_currencyCode_fkey" FOREIGN KEY ("currencyCode") REFERENCES "Currency"("code") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "Transaction" ADD CONSTRAINT "Transaction_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "Transaction" ADD CONSTRAINT "Transaction_accountId_fkey" FOREIGN KEY ("accountId") REFERENCES "Account"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "Transaction" ADD CONSTRAINT "Transaction_currencyCode_fkey" FOREIGN KEY ("currencyCode") REFERENCES "Currency"("code") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "Transaction" ADD CONSTRAINT "Transaction_transferId_fkey" FOREIGN KEY ("transferId") REFERENCES "Transfer"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "LedgerEntry" ADD CONSTRAINT "LedgerEntry_transactionId_fkey" FOREIGN KEY ("transactionId") REFERENCES "Transaction"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "LedgerEntry" ADD CONSTRAINT "LedgerEntry_accountId_fkey" FOREIGN KEY ("accountId") REFERENCES "Account"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "Transfer" ADD CONSTRAINT "Transfer_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "Transfer" ADD CONSTRAINT "Transfer_sourceAccountId_fkey" FOREIGN KEY ("sourceAccountId") REFERENCES "Account"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "Transfer" ADD CONSTRAINT "Transfer_destinationAccountId_fkey" FOREIGN KEY ("destinationAccountId") REFERENCES "Account"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "FxRate" ADD CONSTRAINT "FxRate_baseCode_fkey" FOREIGN KEY ("baseCode") REFERENCES "Currency"("code") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "FxRate" ADD CONSTRAINT "FxRate_quoteCode_fkey" FOREIGN KEY ("quoteCode") REFERENCES "Currency"("code") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "FxSnapshot" ADD CONSTRAINT "FxSnapshot_transferId_fkey" FOREIGN KEY ("transferId") REFERENCES "Transfer"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "FxSnapshotRate" ADD CONSTRAINT "FxSnapshotRate_snapshotId_fkey" FOREIGN KEY ("snapshotId") REFERENCES "FxSnapshot"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "RefreshSession" ADD CONSTRAINT "RefreshSession_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "PasswordResetToken" ADD CONSTRAINT "PasswordResetToken_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "AuditEvent" ADD CONSTRAINT "AuditEvent_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "IdempotencyKey" ADD CONSTRAINT "IdempotencyKey_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE CASCADE ON UPDATE CASCADE;
