packages:
  - apps/*
  - packages/*
allowBuilds:
  '@prisma/engines': set this to true or false
  esbuild: set this to true or false
  prisma: set this to true or false
minimumReleaseAgeExclude:
  - '@expo/cli@57.0.19'
  - '@expo/inline-modules@0.1.7'
  - '@expo/local-build-cache-provider@57.0.8'
  - '@expo/log-box@57.0.4'
  - '@expo/metro-config@57.0.11'
  - '@expo/metro-runtime@57.0.14'
  - '@expo/prebuild-config@57.0.15'
  - '@expo/router-server@57.0.8'
  - '@nestjs/common@12.0.1'
  - '@nestjs/core@12.0.1'
  - '@nestjs/platform-express@12.0.1'
  - babel-preset-expo@57.0.9
  - expo-asset@57.0.15
  - expo-constants@57.0.15
  - expo-file-system@57.0.6
  - expo-modules-autolinking@57.0.12
  - expo-modules-core@57.0.14
  - expo-modules-jsi@57.0.6
  - expo@57.0.17
