import { StyleSheet } from 'react-native';
import { APP_COLORS as colors } from '../../features/auth-screen-theme';

export const styles = StyleSheet.create({
  page: {
    flexGrow: 1,
    backgroundColor: colors.canvas,
    paddingHorizontal: 20,
    paddingTop: 24,
    paddingBottom: 48,
  },
  content: { alignSelf: 'center', gap: 20, maxWidth: 760, width: '100%' },
  header: { alignItems: 'center', flexDirection: 'row', gap: 12, justifyContent: 'space-between' },
  heading: { flex: 1, gap: 6, minWidth: 0 },
  title: { color: colors.ink, fontSize: 28, fontWeight: '700' },
  hint: { color: colors.body, fontSize: 14, lineHeight: 20 },
  addLink: {
    alignItems: 'center',
    backgroundColor: colors.primary,
    borderRadius: 8,
    flexDirection: 'row',
    gap: 7,
    justifyContent: 'center',
    minHeight: 44,
    paddingHorizontal: 12,
  },
  addLinkText: { color: colors.surface, fontSize: 13, fontWeight: '700' },
  filters: {
    alignSelf: 'stretch',
    backgroundColor: colors.subtleSurface,
    borderRadius: 12,
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 4,
    padding: 4,
  },
  filterOption: {
    alignItems: 'center',
    borderRadius: 9,
    flex: 1,
    justifyContent: 'center',
    minHeight: 44,
    minWidth: 76,
    paddingHorizontal: 8,
  },
  filterOptionSelected: { backgroundColor: colors.primary },
  filterLabel: { color: colors.body, fontSize: 13, fontWeight: '600', textAlign: 'center' },
  filterLabelSelected: { color: colors.surface },
  pressed: { opacity: 0.72 },
  state: { alignItems: 'center', gap: 12, paddingVertical: 20 },
  loadingLabel: { color: colors.body, fontSize: 14 },
  error: {
    alignSelf: 'stretch',
    backgroundColor: colors.errorSurface,
    borderRadius: 10,
    color: colors.error,
    fontSize: 15,
    lineHeight: 22,
    padding: 16,
    textAlign: 'center',
  },
  warnings: { gap: 8 },
  warning: {
    backgroundColor: colors.warningSurface,
    borderRadius: 8,
    color: colors.warning,
    fontSize: 14,
    lineHeight: 21,
    padding: 10,
  },
  section: { gap: 12 },
  sectionHeader: { alignItems: 'center', flexDirection: 'row', justifyContent: 'space-between' },
  sectionTitle: { color: colors.ink, fontSize: 19, fontWeight: '700' },
  accountCount: {
    backgroundColor: colors.softSurface,
    borderRadius: 10,
    color: colors.body,
    fontSize: 12,
    fontWeight: '600',
    paddingHorizontal: 9,
    paddingVertical: 5,
  },
  accountList: {
    backgroundColor: colors.surface,
    borderColor: colors.border,
    borderRadius: 12,
    borderWidth: 1,
    overflow: 'hidden',
  },
  accountGroup: { paddingHorizontal: 16, paddingTop: 14 },
  bankGroupName: { color: colors.primary, fontSize: 13, fontWeight: '700', paddingBottom: 4 },
  accountRow: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 12,
    justifyContent: 'space-between',
    minHeight: 64,
    paddingVertical: 12,
  },
  accountRowDivider: { borderBottomColor: colors.border, borderBottomWidth: 1 },
  accountInfo: { flex: 1, gap: 4, minWidth: 0 },
  accountName: { color: colors.ink, fontSize: 15, fontWeight: '600' },
  accountCurrency: { color: colors.body, fontSize: 12, fontWeight: '600' },
  accountBalance: {
    color: colors.ink,
    flexShrink: 1,
    fontSize: 15,
    fontVariant: ['tabular-nums'],
    fontWeight: '700',
    textAlign: 'right',
  },
  emptyState: { backgroundColor: colors.softSurface, borderRadius: 12, gap: 8, padding: 18 },
  emptyTitle: { color: colors.ink, fontSize: 16, fontWeight: '600' },
  emptyCopy: { color: colors.body, fontSize: 14, lineHeight: 21 },
});
