import { StyleSheet } from 'react-native';
import { APP_COLORS as colors } from './auth-screen-theme';

export const styles = StyleSheet.create({
  dashboardRoot: { flex: 1, backgroundColor: colors.canvas },
  canvas: { backgroundColor: colors.canvas },
  center: { flex: 1, alignItems: 'center', justifyContent: 'center', padding: 24, gap: 12 },
  loadingLabel: { color: colors.body, fontSize: 14 },
  error: {
    backgroundColor: colors.errorSurface,
    borderRadius: 10,
    color: colors.error,
    fontSize: 16,
    padding: 16,
    textAlign: 'center',
  },
  page: { flexGrow: 1, paddingTop: 12, paddingBottom: 100 },
  content: { width: '100%', alignSelf: 'center', gap: 18 },
  columns: { gap: 18 },
  columnsWide: { flexDirection: 'row', alignItems: 'flex-start' },
  primaryColumn: { flex: 1.7, minWidth: 0, gap: 18 },
  secondaryColumn: { flex: 1, minWidth: 0, gap: 18 },
  header: { alignItems: 'center', flexDirection: 'row', justifyContent: 'space-between' },
  brand: { alignItems: 'center', flexDirection: 'row', gap: 10 },
  brandMark: {
    alignItems: 'center',
    backgroundColor: colors.primary,
    borderRadius: 12,
    height: 38,
    justifyContent: 'center',
    width: 38,
  },
  brandMarkText: { color: colors.surface, fontSize: 21, fontWeight: '700' },
  brandWords: { gap: 1 },
  brandName: { color: colors.ink, fontSize: 17, fontWeight: '700' },
  brandCaption: { color: colors.muted, fontSize: 12 },
  pageLabel: { color: colors.body, fontSize: 14, fontWeight: '600' },
  summary: { alignItems: 'center', gap: 7, paddingVertical: 16 },
  sectionLabel: { color: colors.body, fontSize: 14, fontWeight: '600' },
  total: {
    color: colors.ink,
    fontSize: 36,
    fontWeight: '700',
    lineHeight: 44,
    fontVariant: ['tabular-nums'],
    textAlign: 'center',
  },
  totalCurrency: { color: colors.body, fontSize: 17, fontWeight: '600' },
  currencySelector: {
    flexDirection: 'row',
    backgroundColor: colors.subtleSurface,
    borderRadius: 12,
    padding: 4,
    gap: 4,
    alignSelf: 'center',
  },
  currencyOption: {
    minWidth: 64,
    minHeight: 44,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 9,
    paddingHorizontal: 10,
  },
  currencyOptionSelected: { backgroundColor: colors.primary },
  currencyOptionText: { color: colors.body, fontSize: 14, fontWeight: '700' },
  currencyOptionTextSelected: { color: colors.surface },
  comparisonChange: {
    color: colors.primary,
    fontSize: 15,
    fontWeight: '700',
    textAlign: 'center',
    fontVariant: ['tabular-nums'],
  },
  equivalent: {
    color: colors.body,
    fontSize: 14,
    fontWeight: '600',
    textAlign: 'center',
    fontVariant: ['tabular-nums'],
  },
  summaryNote: {
    color: colors.body,
    fontSize: 12,
    lineHeight: 18,
    textAlign: 'center',
    alignSelf: 'stretch',
  },
  section: { gap: 10 },
  sectionTitle: { color: colors.ink, fontSize: 19, fontWeight: '700' },
  shortcutRow: { flexDirection: 'row', flexWrap: 'wrap', justifyContent: 'space-around', gap: 6 },
  shortcut: { alignItems: 'center', flex: 1, gap: 6, minHeight: 74, minWidth: 72, paddingVertical: 4 },
  shortcutPressed: { opacity: 0.72 },
  shortcutIcon: {
    alignItems: 'center',
    backgroundColor: colors.softSurface,
    borderRadius: 24,
    height: 48,
    justifyContent: 'center',
    width: 48,
  },
  shortcutGlyph: { color: colors.primary, fontSize: 20, fontWeight: '700' },
  shortcutLabel: { color: colors.body, fontSize: 12, fontWeight: '600', textAlign: 'center' },
  flow: { flexDirection: 'row', gap: 10 },
  flowWide: { flexDirection: 'row' },
  flowItem: {
    backgroundColor: colors.surface,
    borderColor: colors.border,
    borderWidth: 1,
    borderRadius: 12,
    flex: 1,
    minWidth: 0,
    gap: 7,
    padding: 12,
  },
  flowItemWide: { flexBasis: 140 },
  flowItemHeading: { alignItems: 'center', flexDirection: 'row', gap: 4 },
  flowSymbol: { fontSize: 17, fontWeight: '700' },
  income: { color: colors.income },
  expense: { color: colors.expense },
  caption: { color: colors.body, flexShrink: 1, fontSize: 12, fontWeight: '600' },
  value: {
    color: colors.ink,
    fontSize: 18,
    fontWeight: '700',
    fontVariant: ['tabular-nums'],
    flexShrink: 1,
  },
  warning: {
    backgroundColor: colors.warningSurface,
    borderRadius: 8,
    color: colors.warning,
    fontSize: 14,
    lineHeight: 21,
    padding: 10,
    alignSelf: 'stretch',
  },
  sectionHeader: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 8,
    justifyContent: 'space-between',
  },
  accountCount: {
    backgroundColor: colors.softSurface,
    borderRadius: 10,
    color: colors.body,
    fontSize: 12,
    fontWeight: '600',
    paddingHorizontal: 8,
    paddingVertical: 4,
  },
  accountList: { gap: 10, paddingRight: 20 },
  accountListWide: { gap: 10 },
  accountGroup: { width: 230, gap: 8 },
  accountGroupWide: { width: '100%' },
  bankName: { color: colors.primary, fontSize: 14, fontWeight: '700' },
  account: {
    backgroundColor: colors.surface,
    borderColor: colors.border,
    borderWidth: 1,
    borderRadius: 12,
    gap: 7,
    padding: 14,
    width: 230,
  },
  accountWide: { width: '100%' },
  accountHeader: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 8,
    justifyContent: 'space-between',
  },
  accountName: { color: colors.ink, flex: 1, fontSize: 15, fontWeight: '600' },
  accountCurrencyTag: {
    backgroundColor: colors.softSurface,
    borderRadius: 8,
    paddingHorizontal: 8,
    paddingVertical: 4,
  },
  accountCurrencyTagText: { color: colors.primary, fontSize: 11, fontWeight: '700' },
  reportsLink: {
    alignItems: 'center',
    backgroundColor: colors.surface,
    borderColor: colors.border,
    borderWidth: 1,
    borderRadius: 12,
    flexDirection: 'row',
    gap: 12,
    minHeight: 68,
    paddingHorizontal: 14,
    paddingVertical: 12,
  },
  reportsMark: {
    alignItems: 'center',
    backgroundColor: colors.softSurface,
    borderRadius: 9,
    height: 38,
    justifyContent: 'center',
    width: 38,
  },
  reportsMarkText: { color: colors.primary, fontSize: 18, fontWeight: '700' },
  reportsCopy: { flex: 1, gap: 3 },
  reportsTitle: { color: colors.ink, fontSize: 15, fontWeight: '700' },
  reportsHint: { color: colors.body, fontSize: 12 },
  reportsChevron: { color: colors.muted, fontSize: 24 },
  floatingAdd: {
    alignItems: 'center',
    backgroundColor: colors.primary,
    borderRadius: 28,
    bottom: process.env.EXPO_OS === 'web' ? 32 : 20,
    flexDirection: 'row',
    gap: 8,
    justifyContent: 'center',
    minHeight: 56,
    paddingHorizontal: 18,
  },
  floatingAddText: { color: colors.surface, fontSize: 26, fontWeight: '600', lineHeight: 32 },
  floatingAddLabel: { color: colors.surface, fontSize: 14, fontWeight: '700' },
});
